# Generated by Django 4.1 on 2022-08-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=32)),
                ("titleImage", models.ImageField(upload_to="company")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("mainText", models.TextField(blank=True, null=True)),
                (
                    "mapImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/mainImage"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=64)),
                ("titleImage", models.ImageField(upload_to="investors")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvestorOperatingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "indicatorType",
                    models.CharField(
                        choices=[
                            ("financial", "Financial"),
                            ("operating", "Operating"),
                        ],
                        max_length=9,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("residentalRevenue", models.CharField(max_length=5)),
                ("commercialRevenue", models.CharField(max_length=5)),
                ("residentalProceeds", models.CharField(max_length=5)),
                ("salesVolume", models.CharField(max_length=5)),
                ("comissioningVolume", models.CharField(max_length=5)),
                ("mortgageShareOfVolume", models.CharField(max_length=4)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_pages.investor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvestorFinancialInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "indicatorType",
                    models.CharField(
                        choices=[
                            ("financial", "Financial"),
                            ("operating", "Operating"),
                        ],
                        max_length=9,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("revenue", models.CharField(blank=True, max_length=5, null=True)),
                ("editda", models.CharField(blank=True, max_length=5, null=True)),
                ("editdaMargin", models.CharField(blank=True, max_length=5, null=True)),
                ("netProfit", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "netProfitMargin",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("assets", models.CharField(blank=True, max_length=5, null=True)),
                ("debt", models.CharField(blank=True, max_length=5, null=True)),
                ("debtWithNote", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "debtWithNoteByEditda",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("note", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_pages.investor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvestorDisclosureDocs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=64)),
                (
                    "quarter",
                    models.CharField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4)], max_length=1
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("file", models.FileField(upload_to="investors/disclosure_docs/")),
                ("fileType", models.CharField(max_length=8)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_pages.investor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="company/history")),
                ("title", models.CharField(max_length=64)),
                ("desc", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_pages.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyAwards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="company/awards")),
                ("title", models.CharField(max_length=32)),
                ("text", models.CharField(max_length=256)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_pages.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyAchievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="company/achievements")),
                ("title", models.CharField(max_length=32)),
                ("text", models.CharField(max_length=256)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_pages.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyAboutBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=64)),
                ("text", models.TextField()),
                ("shortTitle", models.CharField(max_length=64)),
                ("shortText", models.TextField()),
                ("image", models.ImageField(upload_to="company/about")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_pages.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
