# Generated by Django 4.1 on 2022-08-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investordisclosuredocs",
            name="quarter",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4)]
            ),
        ),
    ]
