# Generated by Django 4.1 on 2022-08-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("pageName", models.CharField(blank=True, max_length=128, null=True)),
                ("pageUrl", models.CharField(blank=True, max_length=256, null=True)),
                ("phone", models.CharField(blank=True, max_length=12, null=True)),
                ("name", models.CharField(blank=True, max_length=32, null=True)),
                ("form", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("new", "New"), ("completed", "Completed")],
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "adminComment",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
