# Generated by Django 4.1 on 2022-08-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("news", "News"), ("promo", "Promo")], max_length=5
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="publications"),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("isVisible", models.BooleanField(blank=True, null=True)),
                ("availableUntill", models.DateTimeField(blank=True, null=True)),
                ("projects", models.ManyToManyField(to="projects.project")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublicationGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="publications/gallery")),
                ("desc", models.TextField()),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.publication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
