# Generated by Django 4.1 on 2022-08-15 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
        ("sections", "__first__"),
        ("floors", "0001_initial"),
        ("projects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("flat", "Flat"),
                            ("larder", "Larder"),
                            ("parking", "Parking"),
                            ("office", "Office"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "layoutType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("studio", "Studio"),
                            ("one_room", "One_room"),
                            ("two_room", "Two_room"),
                            ("three_room", "Three_room"),
                            ("four_room", "Four_room"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("polygonData", models.JSONField(blank=True, null=True)),
                (
                    "space",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "livingSpace",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "spaceWithBalcony",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "balconyCount",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "windowsPosition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("north", "North"),
                            ("northeast", "Northeast"),
                            ("east", "East"),
                            ("southeast", "Southeast"),
                            ("south", "South"),
                            ("southwest", "Southwest"),
                            ("west", "West"),
                            ("northwest", "Northwest"),
                        ],
                        max_length=9,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "buildingId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.building",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="floors.floor",
                    ),
                ),
                (
                    "floorLayout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="floors.floorlayout",
                    ),
                ),
                (
                    "projectId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "sectionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sections.section",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LayoutImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="layout/image")),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="layouts.layout"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LayoutDescriptionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="layout/description/image")),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="layouts.layout"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
