# Generated by Django 4.1 on 2022-08-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("titleImage", models.ImageField(upload_to="page")),
                ("title", models.CharField(max_length=64)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("isVisible", models.BooleanField(blank=True, null=True)),
                ("availableUntill", models.DateTimeField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
