# Generated by Django 4.1 on 2022-08-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sections", "__first__"),
        ("floors", "0001_initial"),
        ("layouts", "0001_initial"),
        ("buildings", "0001_initial"),
        ("projects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("hidden", "Hidden"),
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("sold", "Sold"),
                        ],
                        max_length=9,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                ("meterPrice", models.PositiveIntegerField(blank=True, null=True)),
                ("finishing", models.CharField(blank=True, max_length=32, null=True)),
                ("openDate", models.DateField(blank=True, null=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.building",
                    ),
                ),
                (
                    "entrance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sections.section",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="floors.floor"
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layouts.layout",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectNearerObjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("location", models.CharField(max_length=32)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("culture", "Culture"),
                            ("medicine", "Medicine"),
                            ("education", "Education"),
                            ("shop", "Shop"),
                            ("food", "Food"),
                            ("sport", "Sport"),
                            ("transport", "Transport"),
                            ("kindergarten", "Kindergarten"),
                        ],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("infoLeft", models.CharField(max_length=256)),
                ("infoRight", models.CharField(max_length=256)),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="objects.object"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
