# Generated by Django 4.1 on 2022-08-15 06:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "masterPlanImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="section/master"
                    ),
                ),
                ("polygonData", models.JSONField(blank=True, null=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.building",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
