# Generated by Django 4.1 on 2022-08-15 06:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("hidden", "Hidden"),
                            ("construction", "Construction"),
                            ("ready", "Ready"),
                            ("success", "Success"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "masterPlanImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="building/master"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="building/image"
                    ),
                ),
                ("openDate", models.DateField()),
                (
                    "readyPercent",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("polygonData", models.JSONField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
