# Generated by Django 4.1 on 2022-08-15 06:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sections", "__first__"),
        ("buildings", "0001_initial"),
        ("projects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="FloorLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("schema", models.FileField(upload_to="floor_plan/schema")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="buildings.building",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("number", models.IntegerField()),
                (
                    "schemeImage",
                    models.ImageField(blank=True, null=True, upload_to="floor/schema"),
                ),
                ("polygonData", models.JSONField(blank=True, null=True)),
                (
                    "buildingId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.building",
                    ),
                ),
                (
                    "floorLayout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="floors.floorlayout",
                    ),
                ),
                (
                    "projectId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "sectionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sections.section",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
